apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mediawiki
  name: mw-configmap
data:
  mariadb_url: mariadb-internal-service  # db service name
  mariadb-name: wikimediadb              # mediawiki db name
